### ISSUE TITLE
How do I get it to work?

### ISSUE THREAD

**Issue by jedlikowski** [Emadello/cordova-plugin-CDVTabBar#1]
Is this plugins still maintained? Is it working on iOS 9.3.5? I can't figure out a way to make it work in my cordova app, when I added the code from Readme, I don't see any tabbar in the app :(

**Comment by b4tch** [comment]
Amen.  Little help, please?

**Comment by Emadello** [comment]
Yes it works on 9.3.5, can paste an example of your code?

**Comment by jedlikowski** [comment]
I figured it out, I need to install and actually use your navbar plugin as well to make the tabbar work. Is there any chance you can make them more independent? And maybe add a little help in the readme about when this tabbar creating function should be called? I had a bit of a problem with this as a newbie.

Also, I've noticed that after rotating the screen, the size if the webview is recalculated but without taking into account the tabbar nor the navbar. As a result, webview becomes partially hidden below them.

**Comment by Emadello** [comment]
In the next update I will make them independant as well as other features like navbar background color and tint color.

Also will handle orientations for both.

I will be working on the update tomorrow and will keep you updated.

**Comment by jedlikowski** [comment]
Oh, this is great to hear, thank you :)

**Comment by Emadello** [comment]
Also we are working on both plugins to support Android, it should be soon finished.

**Comment by b4tch** [comment]
Great news, thank you.  Do you have any estimated timescales for the Android version?  I would like to use a native plugin but can't find one that works for both iOS and Android so was just about to build my navigation in HTML instead - I'll hold fire if it's going to be soon :)

**Comment by b4tch** [comment]
@jedlikowski can you please tell me how you got it working?  I have installed the navbar plugin and that is displayed on my app, but still no tabbar.  I have copied the setupnewtabbar and showTab functions from the example and call it like so from my onDeviceReady function: setupnewtabbar('tab1'); (I have also added the navbar example code to the top of this function)

As a side note, when the navbar is displayed, it is not right at the top of the view, it is offset downward, potentially the height of a tabbar, however the area above it is just blank.

**Comment by jedlikowski** [comment]
@b4tch This is part of my onDeviceReady function:

```
// Setting up top navbar
    navbar.create();
    navbar.hideLeftButton();
    navbar.hideRightButton();
    navbar.settitle("");
    navbar.setupLeftButton("Powrót",
        "www/img/icons/png/back.png",
        function(){
            alert('back we go!');
        }
    );
    navbar.showLeftButton();
    navbar.show();
    // Setting up tab bar and setting the first active page to be home
    setupnewtabbar('home');
```

also, this is my setupnewtabbar function:

```
function setupnewtabbar(taborder) {
    var activeTab;
    activeTab = taborder;

    tabbar.createItem("home", "Dodaj", "www/img/icons/png/add-iphone", {
        onSelect: function() {
            var myName = "home";
            if (activeTab != myName) {
                activeTab = myName;
                historyType.push("/");
            }
        }
    });

    tabbar.createItem("dashboard", "Alerty", "www/img/icons/png/alarm-iphone", {
        onSelect: function() {
            var myName = "dashboard";
            if (activeTab != myName) {
                activeTab = myName;
                historyType.push("/dashboard");
            }
        }
    });

    tabbar.createItem("profile", "Profil", "www/img/icons/png/user-iphone", {
        onSelect: function() {
            var myName = "profile";
            if (activeTab != myName) {
                activeTab = myName;
                historyType.push("/profile");
            }
        }
    });

    tabbar.show();
    tabbar.showItems("home", "dashboard", "profile");
    tabbar.selectItem(taborder);
}
```

**Comment by b4tch** [comment]
@jedlikowski Many thanks, I have now found out the cause of my issue - I also have a Google Maps plugin installed (cordova-plugin-googlemaps) and this plugin is conflicting with it somehow.  Removing the Google Maps plugin allows the tab bar to work as expected.

Unfortunately I can't see any errors and the setupnewtabbar completes but then the layout breaks.  I guess I will just have to hope that the new version of this plugin resolves this conflict.

**Comment by jedlikowski** [comment]
@b4tch What do you mean the layout breaks?

**Comment by b4tch** [comment]
Only the navigation bar was showing, and in the wrong place.  Not even the map would display.

However!  I have just got everything working!  Turns out all I needed to do was initialise the nav/tab bars after the map had initialised.  I hope this helps someone else in the same situation.  Again, thanks for your time @jedlikowski :)

**Comment by Emadello** [comment]
An update for both plugins is just released, now they are independent.

Still the android version is not included, but it's coming soon for navbar and will be followed by tabbar.
