### ISSUE TITLE
How to set tabor selection

### ISSUE THREAD

**Issue by GayathriKotte** [Emadello/cordova-plugin-CDVTabBar#2]
How to set tabor selection

**Comment by Emadello** [comment]
You mean the icon color?

**Comment by GayathriKotte** [comment]
yes..I need to reset tab bar selection.
Thanks.

**Comment by Emadello** [comment]
In TabBar.m

From line 177 to line 181

```
[tabBar setTintColor:[UIColor colorWithRed:218.0/255.0 green:33.0/255.0 blue:39.0/255.0 alpha:1.0]];
[tabBar setSelectedImageTintColor:[UIColor redColor]];
```

Change these to your desired color

**Comment by GayathriKotte** [comment]
Hi..
From Javascript side I need to reset the selected tab.
Is there any API to do that?

**Comment by Emadello** [comment]
You can try pass unassigned tab title to taborder, will add it in the next versions to easily do it with javascript

**Comment by GayathriKotte** [comment]
Hi Emadello,
Tabbar is not show in landscape mode. Please let me know how to get it in landscape mode.

Thanks,
Gayathri

**Comment by Emadello** [comment]
Fixing and will release an update soon

**Comment by GayathriKotte** [comment]
Thank you Emadello.
Please let me know tentative date of release.

**Comment by Emadello** [comment]
Most probably at 21 December 2017

**Comment by Emadello** [comment]
@GayathriKotte Check the last version just submitted

**Comment by GayathriKotte** [comment]
Thank you.
Tested  and it is working fine.

**Comment by Emadello** [comment]
@GayathriKotte Awesome

**Comment by GayathriKotte** [comment]
Hi ,
Please let me know how to reset tabbar selected item?
how to pass unassigned tab title to taborder?
Can you please provide JS sample code to implement this? 

Thanks.

**Comment by Emadello** [comment]
just comment the line with : tabbar.selectItem

or you can use the following:
`tabbar.selectItem(0);`

**Comment by GayathriKotte** [comment]
Thank you. Working as expected.
