### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by christoph-schindler** [Emadello/cordova-plugin-CDVTabBar#3]
I need some advice: how to set colors? I tried...
```
tabbar.create({
   selectedImageTintColorRgba: '168,53,57,255',
   tintColorRgba: '44,44,45,255'
});
```
...but nothing happens.

**Comment by Emadello** [comment]
In TabBar.m

From line 177 to line 181

[tabBar setTintColor:[UIColor colorWithRed:218.0/255.0 green:33.0/255.0 blue:39.0/255.0 alpha:1.0]];
[tabBar setSelectedImageTintColor:[UIColor redColor]];
Change these to your desired color

**Comment by christoph-schindler** [comment]
oh okay, i use PhoneGap Build ...so i can't edit TabBar.m

**Comment by Emadello** [comment]
Ok, will release an update soon to modify colors by javascript.
Keep an eye for updates

**Comment by christoph-schindler** [comment]
cool, thanks a lot, I'll do that
