### ISSUE TITLE
iPhoneX support

### ISSUE THREAD

**Issue by jaanguita** [Emadello/cordova-plugin-CDVTabBar#4]
Hi,

do the plugin has support for iPhoneX?
i'm trying to integrate it with my apps, but in iPhoneX the bar is not placed correctly:

![captura de pantalla 2018-05-10 a las 17 00 00](https://user-images.githubusercontent.com/4928600/39876526-b3835c88-5473-11e8-8705-9e6beec94de9.png)

**Comment by Emadello** [comment]
Hello,

The screenshot  you attached shows the tabbar in the correct place in iphone x, please note that the lower part of the iphone is unaccessible and cannot place anything in it.

![a9d7023c-0013-42c5-ba2f-c12b10b87239](https://user-images.githubusercontent.com/1029771/39955789-93137524-55d5-11e8-812a-3d73eab8019b.png)
